name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Login to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build and push Docker image
      - name: Build and push image
        run: |
          docker build -t saadp200/wisecow:v2 .
          docker push saadp200/wisecow:v2

      # 4️⃣ Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      # 5️⃣ Deploy to Kubernetes
     # - name: Deploy to k8s
      #  env:
       #   KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
       # run: |
        #  echo "$KUBE_CONFIG_DATA" | base64 --decode > kubeconfig
         # kubectl --kubeconfig=kubeconfig apply -f k8s/
